name: kieser
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-444.6.beta <3.0.0'
  flutter: '>=3.6.0'

dependencies:
  email_validator:
  flutter:
    sdk: flutter
  flutter_email_sender: 
  model:
    path: './lib/model/'
  path_provider:
  sembast:
  sembast_web:
  settings:
    path: './lib/settings'
  shared_preferences:
  window_manager:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true

  assets:
  - assets/logo/kieser.png

  fonts:
    - family: KieserApp
      fonts:
        - asset: assets/fonts/KieserApp.ttf

flutter_icons:
  image_path_android: "assets/launcher_icon/kieser_icon.png"
  android: true
  ios: true
  image_path: "assets/launcher_icon/kieser_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/launcher_icon/kieser_icon.png"
    background_color:
    theme_color:

